### PR TITLE
Add context (SOFTWARE-4724) and add push (SOFTWARE-4718)

### PR DESCRIPTION
**Pull request by mtru32**

### CODE REVIEW

**Comment by brianhlin** [comment]
@mtru32 could you also add pushing to Harbor to this PR?

**Comment by brianhlin** [comment]
@matyasselmeci any opposition to updating the tag list to the following?

```
hub.opensciencegrid.org/opensciencegrid/koji-builder:release
hub.opensciencegrid.org/opensciencegrid/koji-builder:release-<timestamp>
docker.io/opensciencegrid/koji-builder:release
docker.io/opensciencegrid/koji-builder:release-<timestamp>
```

And updating https://github.com/opensciencegrid/docker-koji-builder/blob/main/Dockerfile#L1 to 

```
FROM opensciencegrid/software-base:3.6-el8-release
```

**Comment by matyasselmeci** [comment]
Nope, go for it.

**Comment by brianhlin** [comment]
@mtru32 I forgot the comment that I posted above. Let's just go with `release` instead of `devops`/`devops-itb` as the tags.

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
